spring:
  application:
    name: dongnae-moa
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dongnaemoa}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345678!}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

jwt:
  secret: ${JWT_SECRET:this-is-test-jwt-secret-lets-win-the-geeks-hackathon}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:10800000}

groq:
  api-key: ${GROQ_API_KEY:}

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  secret: ${JWT_SECRET}

sdk:
  swagger:
    enabled: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  paths-to-match: /v1/**
