spring:
  application:
    name: dongnae-moa
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dongnaemoa}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
